DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ingest_status') THEN
        CREATE TYPE ingest_status AS ENUM (
            'ready',
            'metadata_only',
            'abstract_missing',
            'fetch_failed'
        );
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_job_status') THEN
        CREATE TYPE import_job_status AS ENUM (
            'pending',
            'running',
            'completed',
            'failed'
        );
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS papers (
    id VARCHAR(36) PRIMARY KEY,
    title TEXT NOT NULL,
    url VARCHAR(2048),
    conference_id VARCHAR(36),
    source_page_url VARCHAR(2048),
    venue VARCHAR(255),
    year INTEGER,
    abstract TEXT,
    source_markdown_ref VARCHAR(255),
    ingest_status ingest_status NOT NULL DEFAULT 'abstract_missing',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS conferences (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    normalized_name VARCHAR(255) NOT NULL,
    identity_key VARCHAR(1024) NOT NULL,
    source_page_url VARCHAR(2048),
    year INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_conferences_identity_key ON conferences (identity_key);
CREATE INDEX IF NOT EXISTS ix_conferences_name ON conferences (name);
CREATE INDEX IF NOT EXISTS ix_conferences_normalized_name ON conferences (normalized_name);
CREATE INDEX IF NOT EXISTS ix_conferences_year ON conferences (year);

CREATE UNIQUE INDEX IF NOT EXISTS ix_papers_url ON papers (url);
CREATE INDEX IF NOT EXISTS ix_papers_conference_id ON papers (conference_id);
CREATE INDEX IF NOT EXISTS ix_papers_venue ON papers (venue);
CREATE INDEX IF NOT EXISTS ix_papers_year ON papers (year);

CREATE TABLE IF NOT EXISTS import_jobs (
    id VARCHAR(36) PRIMARY KEY,
    source_name VARCHAR(255),
    status import_job_status NOT NULL DEFAULT 'pending',
    stage VARCHAR(64),
    stage_message TEXT,
    parsed_count INTEGER NOT NULL DEFAULT 0,
    processed_count INTEGER NOT NULL DEFAULT 0,
    imported_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    failed_count INTEGER NOT NULL DEFAULT 0,
    abstract_missing_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS paper_embeddings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id VARCHAR(36) NOT NULL REFERENCES papers (id) ON DELETE CASCADE,
    embedding VECTOR(1536) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_paper_embeddings_paper_id UNIQUE (paper_id)
);

CREATE INDEX IF NOT EXISTS ix_paper_embeddings_paper_id ON paper_embeddings (paper_id);
